### ISSUE TITLE
The code requires GLIBCXX_3.4.29 to run

### ISSUE THREAD

**Issue by chudur-budur** [intel-staging/torch-mlir#29]
If the correct `GLIBCXX` is not on the system, the e2e testing code doesn't run. Gives this error:

```bash
(torch-mlir) user@pc:/localdisk/work/$USER/torch-mlir/project/pt1 | (cpu-proto)>  python -m e2e_testing.main -c "cpuproto" -f "MLP_basic" -v -s --dump all --enable-timer
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/localdisk/work/$USER/torch-mlir/projects/pt1/e2e_testing/main.py", line 16, in <module>
    from torch_mlir_e2e_test.configs import (
  File "/localdisk/work/$USER/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/configs/__init__.py", line 6, in <module>
    from .lazy_tensor_core import LazyTensorCoreTestConfig
  File "/localdisk/work/$USER/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir_e2e_test/configs/lazy_tensor_core.py", line 6, in <module>
    import torch_mlir._mlir_libs._REFERENCE_LAZY_BACKEND as lazy_backend
  File "/localdisk/work/$USER/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 19, in <module>
    from .compiler_utils import run_pipeline_with_repro_report
  File "/localdisk/work/$USER/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 11, in <module>
    from torch_mlir.passmanager import PassManager
  File "/localdisk/work/$USER/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/passmanager.py", line 5, in <module>
    from ._mlir_libs._mlir.passmanager import *
  File "/localdisk/work/$USER/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/_mlir_libs/__init__.py", line 179, in <module>
    _site_initialize()
  File "/localdisk/work/$USER/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/_mlir_libs/__init__.py", line 78, in _site_initialize
    from ._mlir import ir
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /localdisk/work/$USER/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/_mlir_libs/_mlir.cpython-311-x86_64-linux-gnu.so
```

**Comment by chudur-budur** [comment]
The workaround is to install `libgcc` if it's not on the system.

```bash
(torch-mlir) user@pc:~/ conda install anaconda::libgcc
```

and set `LD_LIBRARY_PATH` to corresponding conda env path:

```bash
export LD_LIBRARY_PATH=/localdisk/work/$USER/opt/miniconda3/envs/torch-mlir/lib:$LD_LIBRARY_PATH
```

Then it works.
